# K?t n?i SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=task_management_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123

# T? ??ng c?p nh?t b?ng (update là l?a ch?n an toàn nh?t)
spring.jpa.hibernate.ddl-auto=update

# CHI?N L??C ??T TÊN: T? ??ng ??i fullName (Java) thành full_name (SQL)
# ?ây là chu?n chung giúp Hibernate làm vi?c m??t mà nh?t
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# Hi?n th? SQL ?? d? Debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ph??ng ng? SQL Server
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Swagger UI Path (Tùy ch?n cho g?n)
springdoc.swagger-ui.path=/swagger